# Generated by Django 4.2.7 on 2023-12-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_detection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='cover_image',
            new_name='image',
        ),
    ]
